// lib/siteConfig.js — SINGLE SOURCE OF TRUTH
// Edit here once — updates everywhere across all pages and schemas.

export const SITE = {
  url:          "https://www.aidla.online",
  name:         "AIDLA",
  legalName:    "AIDLA - Artificial Intelligence Digital Learning Academy",
  tagline:      "Study smarter. Earn coins. Build your future.",
  description:  "AIDLA is Pakistan #1 AI powered learning platform offering free courses, daily quizzes, AI tools, career resources, AIDLA Coins, and learner rewards — built for Pakistani students and job seekers.",
  logo:         "https://www.aidla.online/logo.png",
  ogImage:      "https://www.aidla.online/og-home.jpg",
  image: "https://www.aidla.online/og-home.jpg",
  priceRange: "Free",
  phone:        "+923044678929",
  email:        "ceo@aidla.online",
  foundingDate: "2026-02-01",
  launchDate:   "2026-03-01",
  users:        "500+",
  language:     ["en", "ur"],
  locale:       "en_PK",
  twitterHandle:"@AIDLA_online",
  address: {
    street:      "Peshawar",
    locality:    "Peshawar",
    region:      "Khyber Pakhtunkhwa",
    postalCode:  "25000",
    country:     "PK",
  },
  geo: { latitude: "34.0150", longitude: "71.5249" },
  socials: {
    instagram: "https://www.instagram.com/aidla_official/",
    facebook:  "https://www.facebook.com/profile.php?id=61586195563121",
    linkedin:  "https://www.linkedin.com/company/110859146/",
    tiktok:    "https://www.tiktok.com/@aidla_official",
    twitter:   "https://twitter.com/aidla_official",
    youtube:   "https://www.youtube.com/@aidla_official",
  },
};

export const FOUNDER = {
  fullName:      "Engineer Muhammad Zubair Afridi",
  legalName:     "Muhammad Zubair",
  givenName:     "Zubair",
  familyName:    "Afridi",
  honorific:     "Engineer",
  alternateName: ["Muhammad Zubair Afridi", "Engr. Zubair Afridi", "Zubair Afridi"],
  jobTitle:      "Founder & CEO of AIDLA | Electrical Engineer | Entrepreneur",
  description:   "Engineer Muhammad Zubair Afridi is a Gold Medalist Electrical Engineer, entrepreneur, and technology founder from Peshawar, Khyber Pakhtunkhwa, Pakistan. He is the Founder and CEO of AIDLA (Artificial Intelligence Digital Learning Academy), Pakistan's #1 AI-powered learning platform, and CEO of Syed Solar Energy. He holds a BSc in Electrical Engineering from Sarhad University of Science and Information Technology (SUIT) with a CGPA of 3.67, is the batch topper of 2020–2024, and is registered with the Pakistan Engineering Council (PEC) as Electrical Engineer ELECT/109809. He is currently based in Dubai, UAE, working as a Trainee Engineer at Emrill Services LLC.",
  nationality:   "Pakistani",
  gender:        "Male",
  dob:           "2003-01-20",
  birthPlace:    "Peshawar, Khyber Pakhtunkhwa, Pakistan",
  father:        "Syed Ur Rehman",
  tribe:         "Afridi — Hassan Khel, Adam Khel, Khyber Pakhtunkhwa",
  image:         "https://www.aidla.online/founder-zubair-afridi.jpg",
  phone:         "+923044678929",
  email:         "ceo@aidla.online",
  pecReg:        "ELECT/109809",
  cgpa:          "3.67",
  address: {
    street:    "Sheikh Nala Pasani, P/O Sherkera",
    locality:  "Peshawar",
    region:    "Khyber Pakhtunkhwa",
    postalCode:"24960",
    country:   "PK",
  },
  education: [
    {
      type:        "Secondary School Certificate — Science",
      institution: "Umar Bin Khattab Education Academy, Hassan Khel Sub-Division, FR Peshawar",
      start:       "2016", end: "2018",
    },
    {
      type:        "Higher Secondary School Certificate — FSc Pre-Engineering",
      institution: "Govt Higher Secondary School Sama, Hassan Khel Sub-Division, FR Peshawar",
      start:       "2018", end: "2020",
    },
    {
      type:        "BSc Electrical Engineering — Major: Power Systems",
      institution: "Sarhad University of Science and Information Technology (SUIT), Peshawar",
      start:       "2020", end: "2024",
      gpa:         "3.67",
      distinction: "Gold Medalist — Batch Topper 2020–2024",
    },
  ],
  fyp: {
    title:       "Design and Development of Smart Intelligent Solar PV Cleaning Robot",
    description: "An autonomous AI-powered solar panel cleaning robot. Funded by Ignite (Ministry of IT, Govt of Pakistan) with PKR 88,597. Shortlisted for DOST KP funding.",
    thesisUrl:   "https://www.aidla.online/resources/design-development-of-smart-solar-pv-cleaning-robot-thesis-by-muhammad-zubair-afridi",
    funding:     "PKR 88,597",
    funder:      "Ignite — National Technology Fund, Government of Pakistan",
    fundDate:    "2025-02-13",
  },
  career: [
    {
      role: "Trainee Electrical Engineer", company: "Ziewnic Solar Energy",
      start: "2024-10-01", end: "2024-12-31", location: "Pakistan",
    },
    {
      role: "CEO & Co-Founder", company: "Syed Solar Energy",
      start: "2025-04-01", location: "Peshawar, KPK, Pakistan",
      url: "https://syedsolarenergy.com/",
    },
    {
      role: "Trainee Engineer", company: "Emrill Services LLC",
      start: "2025-10-11", location: "Dubai, UAE",
    },
    {
      role: "Founder & CEO", company: "AIDLA",
      start: "2026-02-01", location: "Peshawar, KPK, Pakistan",
      url: "https://www.aidla.online",
    },
  ],
  awards: [
    {
      name:    "Gold Medal — Batch Topper BSc Electrical Engineering 2020–2024",
      issuer:  "Governor of Khyber Pakhtunkhwa & Vice Chancellor, SUIT",
      date:    "2025-06-19",
      location:"Shiraz Arena, Deans Trade Center, Peshawar",
    },
    {
      name:    "Winner — International Solar Expo 2024, Projects & Ideas Competition",
      issuer:  "Sarhad Chamber of Commerce & Sunsaviour",
      date:    "2024-06-01",
      refs:    ["https://www.linkedin.com/posts/sarhad-university-of-science-and-it-peshawar-860b6928b_congratulations-achievement-solarexpo2024-ugcPost-7203472661329399809-fOw3","https://www.facebook.com/share/1HVhdj2Nf3/"],
    },
    {
      name:    "2nd Position — 1st KPK Engineering Projects Expo",
      issuer:  "Pakistan Engineering Council (PEC)",
      date:    "2024-07-01",
      refs:    ["https://www.linkedin.com/posts/verifiedpakistanrecorder_meet-muhammad-zubair-afridi-a-talented-student-activity-7222234442163970050-lL03","https://www.facebook.com/share/p/1U5Lsitaxn/"],
    },
    {
      name:   "Winner — Inter-Departmental Projects Exhibition",
      issuer: "ORIC-SUIT", date: "2024-05-14", location: "SUIT, Peshawar",
    },
    {
      name:   "Best Student of the Year",
      issuer: "FATA Students Federation", date: "2023-01-01",
    },
    {
      name:   "Ignite National Technology Fund Research Grant — PKR 88,597",
      issuer: "Ignite, Ministry of IT & Telecom, Government of Pakistan",
      date:   "2025-02-13",
    },
    {
      name:   "Shortlisted — DOST KP Research Funding",
      issuer: "Directorate of Science and Technology, Khyber Pakhtunkhwa",
    },
    {
      name:    "IEEEP National Projects Exhibition — Karachi",
      issuer:  "Institution of Electrical and Electronics Engineers Pakistan (IEEEP)",
      date:    "2024-09-09", location: "Karachi Expo Center",
      refs:    ["https://www.linkedin.com/posts/sarhad-university-of-science-and-information-technology-peshawar_ieeep2024-sustainability-innovation-activity-7240958229290139648-ECH0"],
    },
  ],
  media: [
    { type: "TV Interview", title: "SUIT TV Interview", url: "https://youtu.be/p8ppTk-awcE?si=ceAiQmCKijGU9A_M" },
    { type: "Conference",   title: "CEO Minds Conference, Islamabad", url: "https://www.facebook.com/share/p/18W2BdyQ2P/" },
  ],
  socials: {
    linkedin:   "https://www.linkedin.com/in/muhammad-zubair-afridi-191319216/",
    facebook:   "https://www.facebook.com/engrzubairafridi/",
    instagram:  "https://www.instagram.com/muhammad.zubair.afridi/",
    tiktok:     "https://vm.tiktok.com/ZS9FaEsvPFScY-AzFuw/",
    youtube:    "https://www.youtube.com/@engrmuhammadzubairafridi",
    googleSite: "https://sites.google.com/view/muhammadzubairafridi/home",
    thesis:     "https://www.aidla.online/resources/design-development-of-smart-solar-pv-cleaning-robot-thesis-by-muhammad-zubair-afridi",
    suitTV:     "https://youtu.be/p8ppTk-awcE?si=ceAiQmCKijGU9A_M",
  },
};

export const SYED_SOLAR = {
  name:        "Syed Solar Energy",
  url:         "https://syedsolarenergy.com/",
  mapsUrl:     "https://share.google/VeDA1fMwmWC6rBYmB",
  foundingDate:"2025-04-01",
  openingDate: "2025-04-14",
  description: "Syed Solar Energy is a solar energy company in Peshawar, KPK, Pakistan, offering solar installation, maintenance, and energy solutions. Built on the foundation of Syed UPS and Batteries Repairing Shop, established by Syed Ur Rehman.",
  phone:       "+923044678929",
  image: "https://syedsolarenergy.com/static/media/logo.a241cffef34dcb846b83.png",
  priceRange: "PKR",
  address: {
    street:    "Office B5, 1st Floor, Mustafa Plaza, Near Imtiaz Mall, Ring Road, Custom Chowk",
    locality:  "Peshawar",
    region:    "Khyber Pakhtunkhwa",
    postalCode:"25000",
    country:   "PK",
  },
  geo: { latitude: "34.0150", longitude: "71.5249" },
  team: [
    { role: "Founder",               name: "Syed Ur Rehman",                note: "Founded Syed UPS and Batteries Repairing Shop; legacy extended into solar energy" },
    { role: "CEO",                   name: "Engineer Muhammad Zubair Afridi", linkedin: "https://www.linkedin.com/in/muhammad-zubair-afridi-191319216/" },
    { role: "Co-Founder & Engineer", name: "Muhammad Aqib",                  note: "Co-founded and leads engineering operations" },
  ],
};